name: pro_linter
description: A starting point for Dart libraries or applications.
version: 0.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  
  custom_lint: ^0.7.0
  custom_lint_builder: ^0.7.0
  analyzer: ^6.11.0 #
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0


executables:
  custom_lint: custom_lint